### ISSUE TITLE
Intro not full screen on Safari

### ISSUE THREAD

**Issue by KendrickIW** [nandomoreirame/dotX#14]
The intro section on the homepage does not cover the full screen.

Using Safari version 10.1.1

**Comment by chef-danny-d** [comment]
Add: 
```css
.intro{
display: flex;
height: 100vh;
justify-content: center;
align-content: center;
}
```

This should fix the issue. You can remove ```vertical align``` and ```text-align``` properties from https://github.com/nandomoreirame/dotX/blob/10c77533a67dc0581e0a92da66a4b128053b5382/source/_sass/base/_intro.scss#L11
